import Box from '@mui/material/Box'
import Stack from '@mui/material/Stack'
import Typography from '@mui/material/Typography'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Our Shopping List</title>
        <meta
          name='a shopping list for busy couples that constatly forget theirs at home'
          content='Generated by create next app'
        />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        sx={
          {
            // pt: 4,
            // px: 1,
            // display: 'flex',
            // justifyContent: 'center'
          }
        }
      >
        <Stack>
          <Typography variant='h2' textAlign='center'>
            Our Shopping List
          </Typography>
        </Stack>
      </Box>
    </>
  )
}
